### ISSUE TITLE
How may i remove the arrow shape icon after each link?

### ISSUE THREAD

**Issue by HungryOrc** [tomjohnson1492/documentation-theme-jekyll#115]
Thanks!

**Comment by geneotech** [comment]
Looks like it is enough to remove this section in ``docs/css/customstyles.css``:

```css
/* this part adds an icon after external links, using FontAwesome*/
a[href^="http://"]:after, a[href^="https://"]:after {
    content: "\f08e";
    font-family: FontAwesome;
    font-weight: normal;
    font-style: normal;
    display: inline-block;
    text-decoration: none;
    padding-left: 3px;
}
````
