### ISSUE TITLE
TOC on Generated PDF

### ISSUE THREAD

**Issue by davidPilkington** [tomjohnson1492/documentation-theme-jekyll#146]
I was just wondering if it is possible to have the TOC output more than just the two levels of headers from the sidebar? Apologies up front for not explaining this we.

Currently, I can output two heading levels deep in the TOC

Section heading
>Page
>Page
>Page

What I would like to be able to do is have additional headers added to the Prince generated TOC

Section heading
>Page Heading
>Page Heading
>>Page Subheading
>>Page Subheading

**Update: I took a look through the samplelist.yml document and there appears to be a way to do this using subfolderitems. I will investigate and come back.**

Thanks

**Comment by davidPilkington** [comment]
Hi all,

I was able to get it to work. As an aside, this feature is not well documented.

I was able to figure it out by looking at the samplelist.yml file. However there is a typo, subfolder should read subfolders if you want them to appear in the menu.

Other than this, love this feature!!! 

for those that want to add sub items to the sidebar (and toc). here is an example built on the samplelst.yml file

```
entries:
- title: Sidebar
  product: Product 1
  version: v1.0
  folders:
  - title: Introduction
    output: web
    folderitems:
    - title: Bananas
      output: web, pdf
      type: frontmatter
      url: bananas.html
      subfolders:

      - title: Apples
        output: web
        subfolderitems:
        - title:  Fuji apples
          output: web
          type: frontmatter
          url: fuji_apples.html
      
        - title: Gala apples
          output: web
          type: frontmatter
          url: gala_apples.html
```
