### ISSUE TITLE
Support CommonMark

### ISSUE THREAD

**Issue by noraj** [tomjohnson1492/documentation-theme-jekyll#170]
## Issue

When CommonMark (https://github.com/jekyll/jekyll-commonmark) is used rather than kramdown, the tag page is broken.
So please support CommonMark renderer as well.

## Config

```yml
markdown: CommonMark # CommonMark, kramdown
commonmark:
  options: ["DEFAULT"]
  extensions: ["table", "strikethrough", "autolink"]
```

## with CommonMark

![image](https://user-images.githubusercontent.com/16578570/63653888-19d3fb00-c773-11e9-8fa2-fd5975b1c941.png)

![image](https://user-images.githubusercontent.com/16578570/63653938-f8274380-c773-11e9-831f-cf33fedef072.png)

## with kramdown

![image](https://user-images.githubusercontent.com/16578570/63653901-4851d600-c773-11e9-9f75-6dc3042f24dd.png)

![image](https://user-images.githubusercontent.com/16578570/63653927-ce6e1c80-c773-11e9-975c-5d4d77fdbecd.png)

## Idea

The problem may be due to how `taglogic.hml` and `links.html` are written. Maybe using a kramdown only feature in there.
