### ISSUE TITLE
How do I create a folder with only subfolders

### ISSUE THREAD

**Issue by depst** [tomjohnson1492/documentation-theme-jekyll#192]
According to the docs:
>If you need a hierarchy that has a folder that contains other folders and no loose topics, use a blank - item 

I can't get that to work to create a folder that contains subfolders but no loose topics. I.e., I want the Mzone folder to contain just the Deploy, Phases, and Considerations subfolders. I want to get rid of the Start Here standalone topic.

![image](https://user-images.githubusercontent.com/36451342/76000408-56e02d80-5f0c-11ea-8809-58521941dda2.png)

Here's my sidebar.yml file. How can I get rid of the standalone topic under Mzone?

```
entries:
- title: sidebar-runbooks
  #product: Features
  folders:
  
  - title: Runbooks
    output: web
    folderitems:

    - title: Overview
      url: /rbk-overview.html
      output: web


  - title: Mzone
    output: web
    folderitems:

    - title: Start Here
      url: /searching.html
      output: web
      
      subfolders:
      - title: Deploy
        output: web
        subfolderitems:

        - title: Core Network
          url: /tag_formatting.html
          output: web

        - title: xCAT0
          url: /tag_navigation.html
          output: web

```
