### ISSUE TITLE
Is the YAML in the democode valid YAML?

### ISSUE THREAD

**Issue by tony-shannon** [tomjohnson1492/documentation-theme-jekyll#79]
Hi, 
Very many thanks for all your work on this excellent codebase. It is a great job.

A question/issue re YAML please.
On editing some of the sidebar YAML files in the _data/ folder, am getting a build error on github pages.
So to troubleshoot the YAML syntax was trying to use a YAML validator such as http://beautifytools.com/yaml-validator.php

However if I put this yaml from your working demo code;
https://github.com/tomjohnson1492/documentation-theme-jekyll/blob/gh-pages/_data/sidebars/home_sidebar.yml
into that tool, am getting an error.
"Error : Unable to parse.
Line : 6    - title: Products"

So am struggling to work from a basic yaml syntax that is known to be valid YAML

Am assuming this is not completely unknown to you/others?

many thanks in advance
Tony

**Comment by tony-shannon** [comment]
I think the issue may be that line breaks (spaces) are not liked in the YAML validators

so instead of ;
```
entries:
- title: Sidebar
  levels: one
  folders:

  - title: Products
    output: web
    folderitems:
    - title: News
      url: /news.html
      output: web
    - title: Theme instructions
      url: /mydoc_introduction.html
      output: web
    - title: Product 1
      url: /p1_landing_page.html
      output: web
    - title: Product 2
      url: /p2_landing_page.html
      output: web
```

which fails the YAML validator..
this seems to pass;
```
entries:
- title: Sidebar
  levels: one
  folders:
  - title: Products
    output: web
    folderitems:
    - title: News
      url: /news.html
      output: web
    - title: Theme instructions
      url: /mydoc_introduction.html
      output: web
    - title: Product 1
      url: /p1_landing_page.html
      output: web
    - title: Product 2
      url: /p2_landing_page.html
      output: web
```
Now I can use the YAML validator ok.
thanks
